version: '3.7'

services:
  library-app:
    container_name: library-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    links:
        - couchdb
  couchdb:
    image: apache/couchdb:2
    ports:
      - "15984:5984"
    volumes: 
      - ./data/couchdb/db:/opt/couchdb/data
      - ./data/couchdb/config:/opt/couchdb/etc/local.d
    environment:
      - COUCHDB_USER=myuser
      - COUCHDB_PASSWORD=mypassword